global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'report-generator'
    static_configs:
      - targets: ['report-generator:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s